Update _index.md
Changed from `apply` to `create` due to the declarative nature of `apply`. You can not use `generateName` with `apply`.
The error that happens is:

```
❯ kubectl apply -f taskRun.yml
error: error when retrieving current configuration of:
Resource: "tekton.dev/v1beta1, Resource=taskruns", GroupVersionKind: "tekton.dev/v1beta1, Kind=TaskRun"
Name: "", Namespace: "hello-world-pipeline"
from server for: "taskRun.yml": resource name may not be empty
```
The following is the correct behavior. 
```
❯ kubectl create -f taskRun.yml
taskrun.tekton.dev/echo-run-c5dtm created
```
Please look at:  https://github.com/kubernetes/kubernetes/issues/44501#issuecomment-294255660